name: Build & Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build and Test (iOS)
    runs-on: macos-14

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Select Xcode version
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: 'latest-stable'

      - name: Install SwiftLint
        run: brew install swiftlint

      - name: Run SwiftLint
        run: swiftlint

      - name: Build & test (iOS)
        run: |
          xcodebuild test \
            -project WineColor.xcodeproj \
            -scheme WineColor \
            -destination 'platform=iOS Simulator,name=iPhone 15' \
            -sdk iphonesimulator \
            -enableCodeCoverage YES \
            ONLY_ACTIVE_ARCH=YES
