name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    name: Build & Test
    runs-on: macos-latest

    steps:
      - name: Checkout project
        uses: actions/checkout@v4

      - name: Select Xcode version
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: 'latest-stable'

      - name: Install SwiftLint
        run: brew install swiftlint

      - name: Run SwiftLint
        run: swiftlint --strict

      - name: Install dependencies
        run: |
          xcodebuild -resolvePackageDependencies

      - name: Build project
        run: |
          xcodebuild build \
            -scheme WineColor \
            -destination 'platform=iOS Simulator,name=iPhone 15' \
            | xcpretty

      - name: Run unit tests
        run: |
          xcodebuild test \
            -scheme WineColor \
            -destination 'platform=iOS Simulator,name=iPhone 15' \
            | xcpretty
